name: "Space-bot"
description: "Simple app for JetBrains Space notification"
author: "Neveric Eluvia"
inputs:
  app_id:
    description: "ID from authentication page in app settings"
    required: true
  app_secret:
    description: "Secret from authentication page in app settings"
    required: true
  organisation_url:
    description: "Base url of your organisation"
    required: true
  chat_title:
    description: "Chat title to send message to"
    required: false
  message:
    description: "Any message to send. Required chat title to work."
    required: false
  project:
    description: "Name of the project."
    required: false
  issue_numbers:
    description: "Space separated list of target issues. Required project name to work."
    required: false
  tag:
    description: "Any tag to mark issues. Required project name and target issues to work."
    required: false
  commits_titles:
    description: "String of commits titles from logs separated by two pipes '||'. 
    Digits in titles will be used as issue numbers alongside with 'issue_numbers param'"
    required: false
outputs:
  result:
    description: "Result string"
runs:
  using: "docker"
  image: "Dockerfile"